name: DevSecOps CI Pipeline

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'kubernetes/**'  # Ignore changes to this file to prevent loops
      - 'README.md'
      - 'assets/**'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:
  security-prechecks: 
    name: Security Prechecks
    runs-on: ubuntu-latest
    steps:
      # Git Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetch all history for all branches and tags
          
      # Secrets Scanning (Gitleaks)
      - name: Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
      # Dependency & IaC Scan (Trivy FS)
      - name: Trivy FS Scan
        uses: aquasecurity/trivy-action@0.33.1
        with: 
          scan-type: 'fs'
          scan-ref: '.'
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true

  unit-test:
    name: Unit Testing
    needs: security-prechecks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # SetUp NodeJs Env
      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with: 
          node-version: 20
          cache: npm

      # Install Dependencies
      - name: Install Dependencies
        run: npm ci

      # Run Unit Tests
      - name: Run Unit Tests
        run: npm test

  static-testing:
    name: Static Code Quality
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # SonarCloud Analysis
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Quality Gate Enforcement
      - name: SonarCloud Quality Gate
        uses: sonarsource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-artifacts:
    name: Build and Store Artifacts
    runs-on: ubuntu-latest
    needs: static-testing
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # SetUp NodeJs Env
      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with: 
          node-version: 20
          cache: npm
          
      # Install Dependencies
      - name: Install Dependencies
        run: npm ci

      # Build Project
      - name: Build Project
        run: npm run build

      # Upload Artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

  docker:
    name: Container Build & Security
    runs-on: ubuntu-latest
    needs: build-artifacts
    permissions:
      contents: read 
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      IMAGE_TAG: ${{ github.sha }}
    outputs:
      image_tag: ${{ steps.export-image-tag.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      # Download build artifacts
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      # Login to GHCR 
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}
  
      # Build Docker Image
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.ci
          load: true  # load image into the local Docker daemon of this GitHub runner
          push: false
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  
      # Trivy Image Scan
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          severity: CRITICAL,HIGH
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library

      # Push Image
      - name: Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # Export image tag as job output
      - name: Export image tag
        id: export-image-tag
        run: |
          echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT

  update-k8s-manifest:
    name: Update Kubernetes Manifest
    runs-on: ubuntu-latest
    needs: docker
    permissions:
      contents: write   # required to push commit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Update image tag in deployment.yaml
      - name: Update image tag
        run: |
          sed -i "s|image: .*tic-tac-toe-app:.*|image: ghcr.io/atkaridarshan04/tic-tac-toe-app:${{ needs.docker.outputs.image_tag }}|" kubernetes/deployment.yaml

      # Commit and push change
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add kubernetes/deployment.yaml
          git commit -m "chore: Update deployment image tag to ${{ needs.docker.outputs.image_tag }}"
          git push